### ISSUE TITLE
Not working on .net standard 2.0

### ISSUE THREAD

**Issue by krunalc** [mrxten/XamEffects#11]
I installed latest preview version of this package in my .net standard 2.0 project but it doesn't work. Any update expected to support .net standard 2.0?

**Comment by mrxten** [comment]
Hi, what error you got?

**Comment by krunalc** [comment]
I get the warning sign against the nuget package item in Nuget list and none of the assemblies related to package gets loaded

**Comment by mrxten** [comment]
Can you send me concrete text of problem?
As I know netstandard 1.6 is subset of 2.0 and there usually no problems with adding library 1.6 to project 2.0.

**Comment by krunalc** [comment]
I reinstalled the nuget package (1.5.0 pre) and this time it installed without any warning. Then I also installed the same nuget package in my Droid project. In MainActivity.cs, I added line 
            _XamEffects.Droid.Effects.Init();_

In my xamal, I added following line on one of the stacklayout (for testing purpose)

 _<StackLayout xe:TouchEffect.Color="Red">_

Now when I run the project, I get exception when "APP" is loading in main activity :

_LoadApplication(new App());_

following is the stack trace I get:
 at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage (Xamarin.Forms.Page page) [0x0005e] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:315 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:343 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication (Xamarin.Forms.Application application) [0x0025c] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:139 
  at GS3App.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00134] in D:\Projects\GS3\App\GS3App\GS3App.Android\MainActivity.cs:85 

Any idea what could be wrong?

In my code, I have frame inside the stacklayout. I already have tap gesture attached to the frame and what I want is when I press on frame, it should show some change in frame color to indicate that it has been pushed. Is it possible to use XamEffects to achieve this objective?

**Comment by mrxten** [comment]
yes, you can use XamEffects for this objective.
Can you show what you have at 85 line in GS3App.Android\MainActivity.cs

**Comment by krunalc** [comment]
Line no. 85 is                 LoadApplication(new App());

**Comment by mrxten** [comment]
You called XamEffects Init method?

**Comment by krunalc** [comment]
In mainactivity.cs, I did init for XamEffects (as mentioned in my reply above). I also put init code in constructor of the App.xaml.cs
XamEffects.Effects.Init();

**Comment by mrxten** [comment]
As I know, now Android Support libraries nugets used in app contain problems.

**Comment by krunalc** [comment]
May I know the problem? What I did wrong?

**Comment by mrxten** [comment]
Did you create test project? if yes can you show me all your code in archive?

**Comment by enisn** [comment]
Same here with @krunalc  NullReferenceException in MainActivity


06-24 12:53:34.959 I/MonoDroid(14375): UNHANDLED EXCEPTION:
06-24 12:53:35.011 I/MonoDroid(14375): System.NullReferenceException: Object reference not set to an instance of an object.
06-24 12:53:35.012 I/MonoDroid(14375):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage (Xamarin.Forms.Page page) [0x0005e] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:308 
06-24 12:53:35.012 I/MonoDroid(14375):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:336 
06-24 12:53:35.012 I/MonoDroid(14375):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication (Xamarin.Forms.Application application) [0x0026f] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:132 
06-24 12:53:35.012 I/MonoDroid(14375):   at SampleApp.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x0002d] in C:\Users\docto\Source\Repos\SampleApp\SampleApp\SampleApp.Android\MainActivity.cs:23 
06-24 12:53:35.012 I/MonoDroid(14375):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <25661073a35344a89f215a4cf81af37c>:0 
06-24 12:53:35.012 I/MonoDroid(14375):   at (wrapper dynamic-method) System.Object.55a6416c-d83b-48e8-8d17-742469f7d587(intptr,intptr,intptr)
06-24 12:53:35.028 W/art     (14375): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
06-24 12:53:35.031 D/Mono    (14375): DllImport searching in: '__Internal' ('(null)').
06-24 12:53:35.031 D/Mono    (14375): Searching for 'java_interop_jnienv_throw'.
06-24 12:53:35.031 D/Mono    (14375): Probing 'java_interop_jnienv_throw'.
06-24 12:53:35.031 D/Mono    (14375): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

**Comment by enisn** [comment]
It works if MainActivity inherits from **FormsApplicationActivity** but if MainActivity inherits **FormsAppCompatActivity** application crashes. 

Will you add support for **FormsAppCompatActivity** ?

**Comment by mrxten** [comment]
Thanks for contributing, will analyze this.

**Comment by mrxten** [comment]
@enisn I tested in netstandard 2.0 and FormsAppCompatActivity. All is work...
Which version of support libraries do you use?

**Comment by mrxten** [comment]
@enisn also which XF version do you use?

**Comment by enisn** [comment]
I've tried again with XF 3.0.0.482, it works. I couldn't understand why it crashed before. I updated Xamarin.Forms, then **Clean**ed and **Rebuild**ed the project. It works.

**Comment by mrxten** [comment]
@enisn shit happens :)
