### ISSUE TITLE
Have you considered to make a PR to Xamarin.Forms project?

### ISSUE THREAD

**Issue by yunusefendi52** [mrxten/XamEffects#12]
A while ago I just tried your library and it's working really great, and I think I am gonna use it to my own project, have you considered to make a PR to Xamarin.Forms project?

BTW, thank you for making this library 😄

**Comment by mrxten** [comment]
Sorry, what is PR?

**Comment by yunusefendi52** [comment]
PR = Pull Requests

**Comment by mrxten** [comment]
Ah, am think Xamarin will not approve this :)
