### ISSUE TITLE
Check if container is null in IsDisposed

### ISSUE THREAD

**Issue by Stensan** [mrxten/XamEffects#13]
Hi, if the container is gone before the animation ended, the app can crash.

I suggest this fix in TouchEffectPlatform.cs (both plattform projects):
public bool IsDisposed => (Container as IVisualElementRenderer)?.Element == null;
instead of
public bool IsDisposed => ((IVisualElementRenderer)Container).Element == null;

**Comment by mrxten** [comment]
Hmm, yes you right.

Thanks.

**Comment by mrxten** [comment]
Fixed in 1.5.1-pre
