### ISSUE TITLE
How to add TouchEffects in C#

### ISSUE THREAD

**Issue by Uaecrom** [mrxten/XamEffects#14]
Hello, I'm new to Xamarin.forms. I like so much your plugin it works perfectly with XAML. I'm trying to generate some customcontrols inside another customcontrol with C# code directly, but I don't know in this case how can I use XamEffect, can you give me a little help?

**Comment by mrxten** [comment]
Sure

```csharp
var grid = new Grid();

TouchEffect.SetColor(grid, Color.Red);
Commands.SetTap(grid, new Command(() => {
    //some action;
}));
Commands.SetTapParameter(grid, new object());

//or through binding 
grid.SetBinding(TouchEffect.ColorProperty, "binding path");
grid.SetBinding(Commands.TapProperty, "binding path");
grid.SetBinding(Commands.TapParameterProperty, "binding path");
```

**Comment by Uaecrom** [comment]
Thanks a lot !

**Comment by OKameric** [comment]
Is it also possible to remove the effect with C# or via binding ?

**Comment by mrxten** [comment]
Ofc, set Color.Default for remove touch effect
