### ISSUE TITLE
PressedCommand doesn´t work

### ISSUE THREAD

**Issue by joaobose** [mrxten/XamEffects#16]
Pressed command doesn´t trigger for any view, i´ve tried everything, but no sucess.

also, is there a way to "untrack" o "stop detecting" tap? or a way to stop the process that run on other thread that checks for taps of all "setted or affected" objects?

Im chaging objects dinamically and my app stops (crash) if i change an already "thouchAffected" (already configured the binding) object. I think that this is happeing because off the app is looking for "the previous version" of the object (before changing it).

![screenshot 1](https://user-images.githubusercontent.com/35584839/42798229-ccbbd438-8960-11e8-8c3e-8cb7ef6c421e.png)
![screenshot 2](https://user-images.githubusercontent.com/35584839/42798231-cce40a3e-8960-11e8-820f-2158c7418f6a.png)

**Comment by mrxten** [comment]
Hello, it seems that a bug, will analyze this. Try set Color and Tap both in one place in code or xaml.

About untrack tap its good idea, I will add that. Now its not provided.

About changing objects could you send me example of code and exception?

**Comment by mrxten** [comment]
Closed due to age
