### ISSUE TITLE
Add check for null for Container is iOS/TouchEffectPlatform.cs

### ISSUE THREAD

**Issue by bdobreav** [mrxten/XamEffects#17]
Hi, recently had an issue on iOS, I got a null reference for (IVisualElementRenderer)Container when navigating through different pages in an Forms app on iOS, and I fixed it by adding the null conditioning operator. Would be helpful if you could add it in the code so I can use the nuget package.

Thank you 

<img width="605" alt="image" src="https://user-images.githubusercontent.com/8884361/45153283-151ddc00-b1dc-11e8-925c-3042cf08a517.png">

**Comment by bdobreav** [comment]
Nevermind, I just saw this was already fixed in 1.5.1-pre

**Comment by mrxten** [comment]
Hi, thanks for your contributing.
Coming soon will be stable 1.5.1 ;)
