### ISSUE TITLE
Null Reference Exception when enabling Fast Renderers

### ISSUE THREAD

**Issue by jemunk** [mrxten/XamEffects#19]
Is soon as I enable [Fast Renderers](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/fast-renderers) in XF, I get a Null Reference Exception.

If I remove the XamEffects attributes of this image element, my application continues just fine:
```
<Image Source="add_btn"
    HorizontalOptions="End"
    xe:TouchEffect.Color="{StaticResource PrimaryBrandColor}"
    xe:Commands.Tap="{Binding AddNoteCommand}" />
```

**Comment by mrxten** [comment]
You got exception in iOS or Android? Or at both?

**Comment by mrxten** [comment]
Ah, its only for android. Ok I will check.

**Comment by mrxten** [comment]
Also, I think you now can try just wrap Image in ContentView and add effect to wrapper.
Its not good way, but for now its may be will work.

**Comment by jemunk** [comment]
Thanks! That fixed the issue for now.

Thank for a great piece of software! It is very liberating to just add tab events with graphical response to every component.
