### ISSUE TITLE
LongTap command not wokring on Grid

### ISSUE THREAD

**Issue by ivansp** [mrxten/XamEffects#20]
Hello it seems that long tap command is not fired when using it on Grid element.
I am testing on android API 24.

```
<Grid xe:Commands.LongTap="{Binding DownLongCommand}" xe:TouchEffect.Color="Red">
     <Label Text="TEST" />
</Grid>
```

The command is binded to property and the color effect is there, but the actual command from view model is never actually executed.

**Comment by mrxten** [comment]
Xamarin.Forms, XamEffects version?
Did you call init in MainActivity?

**Comment by ivansp** [comment]
Yes I called it following the docs:

```
protected override void OnCreate(Bundle savedInstanceState)
{
        InitilizeLog();
        TabLayoutResource = Resource.Layout.Tabbar;
        ToolbarResource = Resource.Layout.Toolbar;
        base.OnCreate(savedInstanceState);
        XamEffects.Droid.Effects.Init();
        global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
        LoadApplication(new App());
}
```

**Comment by mrxten** [comment]
Xamarin.Forms, XamEffects version?

**Comment by ivansp** [comment]
Xamarin forms 3.1.0.6997729
XamEffects: 1.5.1

**Comment by mrxten** [comment]
Which target API do you set?

**Comment by ivansp** [comment]
Hey sorry for late reply had my hands full with other things during the weekend.
Anyways target frameworks:

Minimum Android version: Android 4.4.87 (API Level 20)
Target Android version: Android 8.1 (API Level 27)
Testing on: Android 7.0 (API Level 24 - Huawei device)

**Comment by mrxten** [comment]
I think you something did wrong, but I will check again

**Comment by mrxten** [comment]
Oh, you right. I checked in XF 3.0+, long tap doesn't work correctly.
Thanks, tomorrow will be fix!

**Comment by mrxten** [comment]
Fixed in 1.5.2. Thanks for contributing

**Comment by ivansp** [comment]
No problem, thanks for the fix :)

**Comment by ThallisonRhanniel** [comment]
Hello. Long tap did not work for me. I am using Prism.

Minimum Android version: Android 5.0 (API Level 21)
Target Android version: Android 8.1 (API Level 27)
Testing on: Android 7.1.2 (API Level 24 - Xiaomi device)
Xamarin Forms: 3.2.0.871581
XamEffects: 1.5.2

**MainPage**
```
xmlns:xe="clr-namespace:XamEffects;assembly=XamEffects"
<Grid HorizontalOptions="Center"
              VerticalOptions="Center"
              HeightRequest="100"
              WidthRequest="200"
              xe:Commands.LongTap="{Binding LongClickCommand}" xe:TouchEffect.Color="Red"
              BackgroundColor="LightGray" >
            <Label Text="Test commands"

                   HorizontalOptions="Center"
                   VerticalOptions="Center"/>
        </Grid>
```

**MainActivity**
```
protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);
            XamEffects.Droid.Effects.Init();          
            global::Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication(new App(new AndroidInitializer()));
        }
```

**Comment by mrxten** [comment]
Oh, will check in xiaomi
