### ISSUE TITLE
First Touch doesn't work

### ISSUE THREAD

**Issue by mak100un** [mrxten/XamEffects#21]
When I tap the grid for the first time, there is no touch effect. And after the second and subsequent touches everything works perfect. If it real to fix this bug?

**Comment by mrxten** [comment]
Hi, version of xameffects and xamarin.forms?
Which platform? device? os version?

**Comment by mak100un** [comment]
xameffects version 1.5.2, Xamarin.Forms version - 3.3.0.967583, target os Andriond, device - Xiaomi mi 5, OS version - API 26 (Android 8.0) (By saying touch effect I mean changing the color of element, commands work normal)

**Comment by mak100un** [comment]
I check how xameffects works on more older devices, particularly, on API 17, everything ok, first touch effect works great)

**Comment by mrxten** [comment]
Ok, also. doesnt work only first touch effect or command not executing too?

**Comment by mak100un** [comment]
Only first touch effect

**Comment by mrxten** [comment]
Ok, thanks. will test in MIUI

**Comment by mrxten** [comment]
Also, could you send me please part of xaml/code-behind where you attached this effect?

**Comment by alex-relov** [comment]
У меня кстати тоже не работает на эмуляторе Android 9, на других версиях не проверял. На симуляторе ios 12.1 работает, но только с использованием классической комманды Command="{Binding test}" (xe:Commands.Tap="{Binding test}" не работает) XF 3.3.0.967583, использую Grid

**Comment by mrxten** [comment]
@alex-relov could you show me your code more with more details?

**Comment by mrxten** [comment]
Fixed in 1.6.0.14-pre
