### ISSUE TITLE
Seems it doesn't work with Xamarin 4.0 (currently in Beta)

### ISSUE THREAD

**Issue by tabrs** [mrxten/XamEffects#24]
Hi, I was not able to make it run on **Xamarin 4** (4.0.0.250467-pre7) on **Samsung Tab 2 Active** (Android 8.1)

XamEffects 1.5.6 referenced using Nuget Package on main project and all platform projects

**MainActivity.cs**
```
        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);

            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);

            LoadApplication(new App());
        }
```

**MainPage.xaml**

XE declaration added
`xmlns:xe="clr-namespace:XamEffects;assembly=XamEffects"`

Then used like this

```
		<StackLayout
			Grid.Column="0"
			Margin="0,4,0,4"
			Orientation="Vertical"
			>

			<Grid
				x:Name="GridEl"
				WidthRequest="48"
				HeightRequest="48"
				xe:TouchEffect.Color="Red"
				BackgroundColor="DarkGray"
				>

				<Label Text="TEST LABEL" />

			</Grid>
		</StackLayout>

```

Project builds and run, but no ripple effect on Android.

I've also tried to define this using C# code, including .SetTap - but still no luck.

Just to be sure, I've additionally tested it on an emulator - same results.

Have a good day.

**Comment by mrxten** [comment]
Thx for reporting. I will check.
btw I planning new version when XF 4.0 will release.

**Comment by mrxten** [comment]
Hi, today did test with first stable release XF 4.0. Is seems all is works with 1.6.2 XamEffects.
If you still have problems - please reopen issue.
