### ISSUE TITLE
ListView Item

### ISSUE THREAD

**Issue by brunohenriquy** [mrxten/XamEffects#25]
Hi Buddy,
Nice work, pretty awesome plugin.

I Implemented it in a ListView and it worked just fine until I scroll a couple of pages down, so when I click an Item, it shows the effect in other items. I uploaded a simple code with the problem if you could take a look. Thanks.
https://github.com/brunohenriquy/ListViewXamEffects

**Comment by mrxten** [comment]
Hi, you got this bug in ios or android or both os?
Also, did you try 1.6.0-pre?

**Comment by brunohenriquy** [comment]
Apparently only in Android. My iOS Simulator lags a lot, but it seems to be ok in iOS.
Yes, It also happens in Android using 1.6.0-pre. Just tested.

**Comment by mrxten** [comment]
Yes, you right. Sometimes in ListView shit happens with RetainElement caching strategy.
Try set CachingStrategy="RecycleElementAndDataTemplate" or CachingStrategy="RecycleElement".
I now just tested your example with this strategy and it seems works.

**Comment by brunohenriquy** [comment]
Wow, Thanks Vladislav.
It worked.
