### ISSUE TITLE
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by songurov** [mrxten/XamEffects#28]
XamEffects.iOS.GestureCollectors

foreach (var valueAction in Collection[gest.View].Actions) {
                valueAction?.Invoke(e);
            }

**Comment by mrxten** [comment]
Which version of lib?
How to to reproduce?

But summary ok, I will check this.

**Comment by mrxten** [comment]
Fixed in 1.6.3
