### ISSUE TITLE
XamEffects not work with AiForms.Layout

### ISSUE THREAD

**Issue by scriptBoris** [mrxten/XamEffects#30]
Xamarin.Forms 3.4.0
XamEffects 1.6.3
AiForms.Layout 1.1.0

Link aiForms.Layout: https://github.com/muak/AiForms.Layouts
![image](https://user-images.githubusercontent.com/29772096/59350870-b4fe2c80-8d4f-11e9-93ee-77f85971f1b7.png)

In run click element - not effect

**Comment by mrxten** [comment]
Hi, effect doesn't work with Frame. Add effect to child

**Comment by scriptBoris** [comment]
![image](https://user-images.githubusercontent.com/29772096/59398256-17901080-8dc2-11e9-8519-a75c5a653df9.png)
@mrxten look, im use it. But result is NullReferenceException

ffimage - this is nuget: https://github.com/luberda-molinet/FFImageLoading

**Comment by scriptBoris** [comment]
@mrxten how use XamEffect with FFimage?

**Comment by mrxten** [comment]
@scriptBoris FFImageLoading using fast renderers. I wrote in readme, views with fast renderers could not work.
There are 2 ways: 
1) Add ContentView between Frame and CachedImage and add effect to it;
or
2) Change Frame to another view, like mine BorderView and add effect to it.

**Comment by scriptBoris** [comment]
![image](https://user-images.githubusercontent.com/29772096/59560123-e6704400-903e-11e9-9805-63381eb3efc1.png)

@mrxten touch effect is worked, but Tap Command not work.

P.S. TapGestureRecognizer - also does not work

**Comment by mrxten** [comment]
Man, why you dont read readme? I specified effect doesn't work with standard gestures, use commands and delete tap gesture recognizer

**Comment by scriptBoris** [comment]
I deleted standard gestures but xe:command still doesn't work.

**Comment by mrxten** [comment]
Make for me example project repo with reproducing problem. I think you made something wrong

**Comment by scriptBoris** [comment]
Later. I will create simulate project and share with you
