### ISSUE TITLE
LongPress Timer

### ISSUE THREAD

**Issue by NRayan** [mrxten/XamEffects#34]
Any way the LongTap command can be fired after a timer, and not just when the user removes the finger ? that would make this Effect even better.

by the way, great work!

**Comment by mrxten** [comment]
There is no any communications between XF and native touch events, but you can add them yourself for Tap/LongTap.

Here:
[Android handler](https://github.com/mrxten/XamEffects/blob/master/src/XamEffects.Droid/GestureCollectors/TouchCollector.cs#L33)
[iOS handler](https://github.com/mrxten/XamEffects/blob/master/src/XamEffects.iOS/CommandsPlatform.cs#L39)
