### ISSUE TITLE
WPF Support

### ISSUE THREAD

**Issue by dhpanteon** [mrxten/XamEffects#37]
Is that work in WPF? 

I have created a project in xamarin form for wpf, android and ios. I need this feature in android. but it's ok, if that will not work in WPF with out any library missing error. Will that work ?

**Comment by mrxten** [comment]
You wanna just add some missing error?

**Comment by dhpanteon** [comment]
I have not implement this lib yet. Just want to confirm that is that work on WPF project ?

**Comment by mrxten** [comment]
No, wpf doesnt supported
