### ISSUE TITLE
Don't work on ContentView, Grid, StackLayout in C#

### ISSUE THREAD

**Issue by gaffkins** [mrxten/XamEffects#4]
Don't work on this(ContentView), layout(Grid or StackLayout). Work only on text (Label)

My code:
public class TabbarButton : ContentView
    {
        public TabbarButton()
        {
            BackgroundColor = Color.LightGray;

            var text = new Label { VerticalOptions = LayoutOptions.Fill, HorizontalOptions = LayoutOptions.FillAndExpand };

            var layout = new Grid
            {
                HorizontalOptions =LayoutOptions.FillAndExpand,
                Children =
                {
                    text
                }

            };
            HorizontalOptions = LayoutOptions.FillAndExpand;
            Content = layout;

            TouchEffect.Init();
            TouchEffect.SetColor(text, Color.Red);

            Commands.SetTap(text, new Command(() => Debug.WriteLine("ELO")));

        }
    }

**Comment by mrxten** [comment]
1. You have to call Init method in native projects, not in XF.
2. Show me pls how you use these effects in ContentView, Grid, StackLayout.

**Comment by gaffkins** [comment]
public class TabbarButton : ContentView
    {
        public TabbarButton()
        {
            BackgroundColor = Color.LightGray;
            HorizontalOptions = LayoutOptions.FillAndExpand;

            var layout = new StackLayout
                    {
                        Children =
                        {
                            new Label {Text = "Test"}
                        }
                    };

            Content = layout;

            TouchEffect.SetColor(layout, Color.Red);

            Commands.SetTap(layout, new Command(() => Debug.WriteLine("ELO")));

        }
    }

**Comment by mrxten** [comment]
What version of XF?

**Comment by gaffkins** [comment]
XF 2.5.0.91635

**Comment by mrxten** [comment]
Ah, yes I still not add support latest XF version...
If you strongly need now use this lib then be patient and change XF version to 2.3.4.*

**Comment by gaffkins** [comment]
Ok, thank you. Some approximate release date?

**Comment by mrxten** [comment]
This week for solve this

**Comment by luismts** [comment]
Same problem here. Doesn't work with BoxView either

**Comment by mrxten** [comment]
@gaffkins, @luismts pls try new version 1.4.0-pre for Xamarin.Forms 2.5+
