### ISSUE TITLE
Android init

### ISSUE THREAD

**Issue by fsantanac** [mrxten/XamEffects#5]
Hi, great plugin. In my ios project work fine but in android no work. Wich is the initialize command for android?

Thanks

**Comment by mrxten** [comment]
Hi, for XF 2.3.4 use version 1.3.3. For this version in Android not need Init.
For XF 2.5+ need version 1.4.0-pre3 and upper, and is there Init.
In MainActivity.OnCreate call `XamEffects.Droid.Effects.Init();`

**Comment by fsantanac** [comment]
Thanks, work fine
