### ISSUE TITLE
1.3.3 init?

### ISSUE THREAD

**Issue by bentmar** [mrxten/XamEffects#6]
Having troubles with version 1.3.3, the ui doesnt react. 

 XamEffects.Droid.Effects.Init(); doesnt exist in this version so im going with    XamEffects.Effects.Init();
is there anything else i have to do?

Im using 1.4 in a different project and it works like a charm

Thanks!

**Comment by mrxten** [comment]
Hi, 1.3.3 is old version for XF 2.3.4.
This version not need android init.
