### ISSUE TITLE
Exception when start application

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [mrxten/XamEffects#8]
Hi Vladislav!

I have a problem with your package. I create a test application and import XamEffects nuget package in PCL and Android project. At first i get a warning with import nuget package.
![image](https://user-images.githubusercontent.com/30652592/39032972-8f5d7aec-4478-11e8-92b1-12864247fd9f.png)

When i try to start application i get an exception in MainActivity:
![image](https://user-images.githubusercontent.com/30652592/39033019-c2bb06b6-4478-11e8-873e-9db9b84cb948.png)

Here is the project in zip archive in Google Drive:
https://drive.google.com/open?id=12EpnzXI0-1EP3ftgkjMMdsQS2-Btneu7

**Comment by mrxten** [comment]
Hi, Nikita!

This shit sometimes happened.
Its problem with Visual Studio.
There few ways to solve problem:
1) Close VS, delete bin/obj in each project in solution, open solution, rebuild.
2) If first way won't help try create not PCL but .NETStandard 1.6/2.0 project with XamEffect ver. 1.5.0-pre

**Comment by Goncharuk-Nikita** [comment]
Yea thanks, the first solution worked
