### ISSUE TITLE
Android Button effect does not work

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [mrxten/XamEffects#9]
Hi Vladislav!

Thanks for your package!
When I attach the effect to Button control, taps are not recognized.

**Comment by mrxten** [comment]
Hi, yes ofc.
Button contains own touch effect. My effect overlaps any taps in any controls.
I strongly not recommend use this effect at controls with own recognizers.

**Comment by Goncharuk-Nikita** [comment]
Ок, can you know how to change the color of the effect of a default button?

**Comment by mrxten** [comment]
https://forums.xamarin.com/discussion/80021/custom-button-style-how

Google it. Many examples.
